<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-gb" xml:lang="en-gb">
<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="en-gb" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="copyright" content="2002-2006 phpBB Group" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="refresh" content="60;url=http://www.dayah.com/toes/forum/viewonline.php?sg=0&amp;sk=b&amp;sd=d&amp;start=0" /><title>Ingrown Toenails Forum &bull; Who is online</title>

<!--
	phpBB style name: prosilver
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by:      
	
	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Enter the page number you wish to go to.:';
	var on_page = '1';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var onload_functions = new Array();
	var onunload_functions = new Array();

	
	/**
	* Find a member
	*/
	function find_username()
	{
				return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (i = 0; i <= onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (i = 0; i <= onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript" src="./styles/prosilver/template/styleswitcher.js"></script>
<script type="text/javascript" src="./styles/prosilver/template/forum_fn.js"></script>

	<link href="./styles/prosilver/theme/print.css" rel="stylesheet" type="text/css" media="print" title="printonly" />
	<link href="./style.php?sid=47ad3fb5862cebfbcd22893a5835519e&amp;id=1&amp;lang=en" rel="stylesheet" type="text/css" media="screen, projection" />

	<link href="./styles/prosilver/theme/normal.css" rel="stylesheet" type="text/css" title="A" />
	<link href="./styles/prosilver/theme/medium.css" rel="alternate stylesheet" type="text/css" title="A+" />
	<link href="./styles/prosilver/theme/large.css" rel="alternate stylesheet" type="text/css" title="A++" />

</head>

<body id="phpbb" class="section-viewonline ltr">

<div id="wrap">
	<a id="top" name="top" accesskey="t"></a>
	<div id="page-header">
		<div class="headerbar">
			<div class="inner"><span class="corners-top"><span></span></span>

			<div id="site-description">
				<a href="./index.php" title="Board index" id="logo"><img src="./styles/prosilver/imageset/site_logo.gif" width="139" height="52" alt="" title="" /></a>
				<h1>Ingrown Toenails Forum</h1>
				<p>The second most common human ailment</p>
				<p style="display: none;"><a href="#start_here">Skip to content</a></p>
			</div>

		
			<span class="corners-bottom"><span></span></span></div>
		</div>

		<div class="navbar">
			<div class="inner"><span class="corners-top"><span></span></span>

			<ul class="linklist navlinks">
				<li><a class="icon-home" href="./index.php" accesskey="h">Board index</a> </li>

				<li class="rightside"><a href="#" onclick="fontsizeup(); return false;" class="fontsize" title="Change font size">Change font size</a></li>

							</ul>

			<ul class="linklist">
								<li class="rightside">
					<a href="./faq.php" title="Frequently Asked Questions" class="icon-faq">FAQ</a>&nbsp; 
									</li>
			</ul>

			<span class="corners-bottom"><span></span></span></div>
		</div>

	</div>

	<a name="start_here"></a>
	<div id="page-body">
		
		 
<h2>There is 1 registered user and 0 hidden users online</h2>
<p>There are 0 guest users online &bull; <a href="./viewonline.php?sg=1">Display guests</a></p>

<ul class="linklist">
	<li class="rightside pagination">Page <strong>1</strong> of <strong>1</strong></li>
</ul>

<div class="forumbg">
	<div class="inner"><span class="corners-top"><span></span></span>
	
	<table class="table1" cellspacing="1">

			<thead>
		<tr>
			<th class="name"><a href="./viewonline.php?sk=a&amp;sd=a&amp;sg=0">Username</a></th>
			<th class="info"><a href="./viewonline.php?sk=c&amp;sd=a&amp;sg=0">Forum location</a></th>
			<th class="active"><a href="./viewonline.php?sk=b&amp;sd=a&amp;sg=0">Last updated</a></th>
		</tr>
		</thead>
		<tbody>
				<tr class="bg2">
			<td><b style="color:#9E8DA7">Alexa [Bot]</b></td>
			<td class="info"><a href="./viewonline.php">Viewing who is online</a></td>
			<td class="active">Mon Oct 15, 2007 1:18 pm</td>
		</tr>
			</tbody>
	</table>
	
	<span class="corners-bottom"><span></span></span></div>
</div>

<p><em>Legend: <a style="color:#AA0000" href="./memberlist.php?mode=group&amp;g=5">Administrators</a>, <a style="color:#00AA00" href="./memberlist.php?mode=group&amp;g=4">Global moderators</a></em></p>
<ul class="linklist">
	<li class="rightside pagination">Page <strong>1</strong> of <strong>1</strong></li>
</ul>

	<form method="post" id="jumpbox" action="./viewforum.php" onsubmit="if(document.jumpbox.f.value == -1){return false;}">

			<fieldset class="jumpbox">
				<label for="f" accesskey="j">Jump to: </label>
			<select name="f" id="f" onchange="if(this.options[this.selectedIndex].value != -1){ document.forms['jumpbox'].submit() }">
							<option value="-1">Select a forum</option>
			<option value="-1">------------------</option>				<option value="1">My first Category</option>
							<option value="2">&nbsp; &nbsp;Stories</option>
							<option value="3">&nbsp; &nbsp;Fears</option>
						</select>
			<input type="submit" value="Go" class="button2" />
		</fieldset>
	</form>

</div>

<div id="page-footer">

	<div class="navbar">
		<div class="inner"><span class="corners-top"><span></span></span>

		<ul class="linklist">
			<li><a class="icon-home" href="./index.php" accesskey="h">Board index</a></li>
							<li class="rightside"><a href="./memberlist.php?mode=leaders">The team</a> &bull; All times are UTC </li>
		</ul>

		<span class="corners-bottom"><span></span></span></div>
	</div>
	
<!--
	We request you retain the full copyright notice below including the link to www.phpbb.com.
	This not only gives respect to the large amount of time given freely by the developers
	but also helps build interest, traffic and use of phpBB3. If you (honestly) cannot retain
	the full copyright we ask you at least leave in place the "Powered by phpBB" line, with
	"phpBB" linked to www.phpbb.com. If you refuse to include even this then support on our
	forums may be affected.

	The phpBB Group : 2006
//-->

	<div class="copyright">Powered by <a href="http://www.phpbb.com/">phpBB</a>  &copy; 2000, 2002, 2005, 2007 phpBB Group
			</div>
</div>

</div>

<div>
	<a id="bottom" name="bottom" accesskey="z"></a>
	</div>

</body>
</html>